name: CI

on:
  push:
    branches:
      - "**"
    tags:
      - "v*"
  pull_request:
    branches:
      - "**"

permissions:
  contents: write
  packages: write

jobs:
  tests:
    name: Unit and integration tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go: ["1.26.5"]

    steps:
      - uses: actions/checkout@v7

      - uses: actions/setup-go@v7
        with:
          go-version: ${{ matrix.go }}

      - name: Run tests
        run: make test+coverage

      - if: ${{ matrix.go == '1.26.5' }}
        uses: shogo82148/actions-goveralls@v1
        with:
          path-to-profile: coverage.txt

  spellcheck:
    name: Spellcheck
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v7

      - uses: actions/setup-go@v7
        with:
          go-version: "1.26.5"
          cache: false

      - name: Run spellcheck
        run: |
          go install github.com/client9/misspell/cmd/misspell@latest
          misspell -error docs

  lint:
    name: Lint
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v7

      - uses: actions/setup-go@v7
        with:
          go-version: "1.26.5"
          cache: false

      - name: Run lint
        uses: golangci/golangci-lint-action@v9
        with:
          version: v2.12.2
          args: --timeout 5m

  govulncheck:
    name: Check vulnerabilities
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v7

      - uses: actions/setup-go@v7
        with:
          go-version: "1.26.5"

      - name: Check vulnerabilities
        uses: golang/govulncheck-action@v1

  build:
    name: Build and release
    runs-on: ubuntu-latest

    # This job can ONLY run for a v* tag push.
    if: ${{ github.event_name == 'push' && startsWith(github.ref, 'refs/tags/v') }}

    needs:
      - tests
      - spellcheck
      - lint
      - govulncheck

    steps:
      - uses: actions/checkout@v7
        with:
          fetch-depth: 0
          submodules: recursive

      - name: Set up Node.js
        uses: actions/setup-node@v7
        with:
          node-version: "24"

      - name: Install PNPM
        uses: pnpm/action-setup@v6
        with:
          version: 11

      - name: Set up Go
        uses: actions/setup-go@v7
        with:
          go-version: "1.26.5"

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build frontend
        run: make build+frontend

      - name: Hide git changes to the goreleaser
        run: git update-index --assume-unchanged ./internal/controller/ui/ui-build/index.html

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v4

      - name: Set GoReleaser previous tag (to non -dev-)
        if: ${{ !contains(github.ref_name, '-dev-') }}
        run: |
          PREVIOUS_TAG=$(git tag --sort=-v:refname \
            | grep -v -- '-dev-' \
            | grep -v -- "^${GITHUB_REF_NAME}$" \
            | head -n 1)

          echo "GORELEASER_PREVIOUS_TAG=$PREVIOUS_TAG" >> "$GITHUB_ENV"
          echo "Previous stable tag: $PREVIOUS_TAG"

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v6
        with:
          distribution: goreleaser
          version: "~> v2"
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Install go-selfupdate
        run: go install github.com/sanbornm/go-selfupdate/cmd/go-selfupdate@latest

      - name: Prepare update binaries
        shell: bash
        run: |
          set -euo pipefail

          rm -rf _bin
          mkdir -p _bin

          tar -xOzf dist/ffmate_Darwin_arm64.tar.gz ffmate > _bin/darwin-arm64
          tar -xOzf dist/ffmate_Linux_x86_64.tar.gz ffmate > _bin/linux-amd64
          tar -xOzf dist/ffmate_Linux_arm64.tar.gz ffmate > _bin/linux-arm64
          tar -xOzf dist/ffmate_Darwin_x86_64.tar.gz ffmate > _bin/darwin-amd64

          unzip -p dist/ffmate_Windows_x86_64.zip ffmate.exe > _bin/windows-amd64
          unzip -p dist/ffmate_Windows_arm64.zip ffmate.exe > _bin/windows-arm64

          chmod +x _bin/darwin-* _bin/linux-*

      - name: Execute go-selfupdate
        shell: bash
        run: |
          set -euo pipefail

          rm -rf _update
          mkdir -p _update

          VERSION="${GITHUB_REF_NAME}"

          ${GOPATH:-$HOME/go}/bin/go-selfupdate \
            -o=_update/ffmate \
            _bin/ \
            "$VERSION"

      - name: Upload update binaries to S3
        uses: jakejarvis/s3-sync-action@master
        with:
          args: --acl public-read --follow-symlinks --delete
        env:
          AWS_S3_BUCKET: ${{ secrets.S3_BUCKET }}
          AWS_ACCESS_KEY_ID: ${{ secrets.S3_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.S3_ACCESS_KEY_SECRET }}
          AWS_REGION: ${{ secrets.S3_REGION }}
          AWS_S3_ENDPOINT: ${{ secrets.S3_ENDPOINT }}
          DEST_DIR: ${{ github.ref == 'refs/heads/main' && '_update' || '_update-dev' }}
          SOURCE_DIR: "_update"