name: CI
on:
  push:
    branches:
      - "**"
    tags-ignore:
      - "v*.*.*"
  pull_request:
    branches:
      - "**"
jobs:
  tests:
    name: Unit and integrations tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go: ["1.25.1"]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go }}
      - name: Run tests
        run: |
          make test+coverage
      - if: ${{ matrix.go == '1.25.1' }}
        uses: shogo82148/actions-goveralls@v1
        with:
          path-to-profile: coverage.txt


  spellcheck:
    name: Spellcheck
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: "1.25.1"
          cache: false
      - name: Run spellcheck
        run: |
          go install github.com/client9/misspell/cmd/misspell@latest
          misspell -error docs

  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: "1.25.1"
          cache: false
      - name: Run lint
        uses: golangci/golangci-lint-action@v8
        with:
          version: v2.4
          args: --timeout 5m

  govulncheck:
    name: Check vulnerabilities
    runs-on: ubuntu-latest
    steps:
      - id: govulncheck
        uses: golang/govulncheck-action@v1
